# docker build -t ghcr.io/tira-io/measure:dev-0.0.2 -f .devcontainer/Dockerfile.dev .
# FROM ghcr.io/tira-io/measure:dev-0.0.1
FROM ubuntu:noble

ARG DEBIAN_FRONTEND=noninteractive

########################################################################################################################
# Install Dependencies                                                                                                 #
########################################################################################################################
USER root
RUN <<EOF
set -e
apt-get update
apt-get -y install clang-18 cmake git sudo

# Needed for the dev environment
apt-get -y install build-essential cppcheck flawfinder doxygen graphviz gdb clang-tidy clang-format

# Dependencies (libssl-dev needed for libgit)
apt-get -y install libssl-dev
EOF

########################################################################################################################
# Python Development                                                                                                   #
########################################################################################################################
USER root
RUN <<EOF
set -e
apt-get update
apt-get -y install python3-pip python3
EOF


########################################################################################################################
# Kotlin Development                                                                                                   #
########################################################################################################################
USER root
RUN <<EOF
set -e
apt-get update
apt-get -y install openjdk-8-jdk openjdk-17-jdk openjdk-21-jdk
# TODO: install kotlin
EOF


########################################################################################################################
# Create User                                                                                                          #
########################################################################################################################
# For some reason, an ubuntu user is created by default.
RUN userdel -r ubuntu || true
# Create new user: "dev" and add it to sudo group
RUN <<EOF
set -e
useradd -ms /bin/bash dev
usermod -aG sudo dev
# Do not ask for password for sudo commands
echo "dev ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
EOF
USER dev